### ISSUE TITLE
Website loads icons slowly

### ISSUE THREAD

**Issue by mmahalwy** [styled-icons/styled-icons#1281]
Thoughts on having tabs for the different packages? I often won't be picking from different packages. Would be nice to be powered by query params. I can help with this if needed

**Comment by jacobwgillespie** [comment]
Totally, we have almost 17k icons now, so the website is starting to reflect that fact. 🙂 

Let me see what I can do, I have a few ideas for performance improvements and agree that having icon pack filters would be super useful 👍

**Comment by mmahalwy** [comment]
awesome! Thanks @jacobwgillespie for this!

**Comment by mmahalwy** [comment]
@jacobwgillespie thoughts on this? I can help here if you need. LMK when :)

**Comment by jacobwgillespie** [comment]
@mmahalwy totally, PRs are 100% welcome. I haven't had a chance to look at improvements yet, and if you'd like to take a look that would be awesome!

I believe the current slowness is probably caused by:

- Each icon pack is code-split into a different JS file. I did this to reduce the size of the overall JS that needs to be downloaded, with the idea that packs could be fetched lazily when they scroll into view, but I think it's actually downloading all the packs at once, which causes the page to freeze until all packs have loaded, and since only X requests are allowed in flight at a time, this is slower than it was originally. Fix is probably making the packs actually lazy-load (or some other ideas below).
- IIRC it computes the search index with `js-search` on startup, which is likely blocking time-to-interactive. Something better would be loading the icons first, then loading the search index, or maybe even looking at offloading the search index to a web worker. It could also be possible to pre-compute the search index as a build step, though that would end up increasing the JS bundle size.

Those would potentially fix the immediate performance freeze at load, though at some point I'd love to have a new version of the UI, now that there are so many icons. Potential features like:

- Possibly list out the pack names on a sidebar on the left, where you could click on a pack name to see only icons from that pack
- Possibly have a way of selecting multiple packs, then only those selected packs would be visible, and search would only apply to the selected packs (so like a pack filter)
- Maybe some way of increasing the icon display density, with a different mechanism for copying the icon names? Like, the tiles are large to accommodate the icon names, but if names appeared on hover, or there was a copy button that appeared on hover, etc., it might be possible to show more icons at once. This idea is still vague, and I'm not sure the accessibility implications of alternate options.
- Generally it would be cool to have more of a "web app" feel for the website, that makes it easy to find icons and drill down to what you want. What's there now was my extremely basic v1.0, which is essentially just a glorified list of everything, which I feel is hitting its scalability limits.

If you're interested in helping with any of the above, or have any other alternate ideas, definitely feel free, I'm happy to assist in any way too!

**Comment by stramel** [comment]
I have also been looking into and working on some website rework in my spare time.

> Each icon pack is code-split into a different JS file. I did this to reduce the size of the overall JS that needs to be downloaded, with the idea that packs could be fetched lazily when they scroll into view, but I think it's actually downloading all the packs at once, which causes the page to freeze until all packs have loaded, and since only X requests are allowed in flight at a time, this is slower than it was originally. Fix is probably making the packs actually lazy-load (or some other ideas below).

This is true, the dynamic imports would have to be wrapped by a function to prevent them all from loading immediately.

> IIRC it computes the search index with js-search on startup, which is likely blocking time-to-interactive. Something better would be loading the icons first, then loading the search index, or maybe even looking at offloading the search index to a web worker. It could also be possible to pre-compute the search index as a build step, though that would end up increasing the JS bundle size.

Yeah I noticed this as well. I think the web worker idea would be good but wouldn't work well for older browsers.


> Generally it would be cool to have more of a "web app" feel for the website

I agree, this would be really cool.

**Comment by AhmedTohamy01** [comment]
@jacobwgillespie 

I have another problem with the slow performance , but not in https://styled-icons.js.org/ , it's in my react project itself.

When i use "npm i styled-icons" it took 15 min. to finish, and after it's  finished i noticed that my react app is loading extremely slower than usual (all pages), does this because i'm using icons from different packs ?

**Comment by AhmedTohamy01** [comment]
@jacobwgillespie 

Thank you for fast reply.

The problem is that i really use different icons from different packs, this library is amazing, it has a lot of pretty icons ...

Is there is anyway to install only the ICON that i need ?

for example: if i need this icon only "@styled-icons/boxicons-logos/Amazon" , should i install all ""@styled-icons/boxicons-logos" just to get 1 icon ?

**Comment by jacobwgillespie** [comment]
No problem! There's not currently a way to install just a single icon, so yes you would want to install `@styled-icons/boxicons-logos` even if you're only using one icon from that pack. 

But that's still a lot lighter than installing everything, there are over 35 different packs included in `styled-icons`.

**Comment by AhmedTohamy01** [comment]
@jacobwgillespie 

Hey man, thank you so much for your clear answer. I wish if i could select the icons which i like from any pack :) 

By the way, i found this slowness when i used styled-icons in NEXT.JS also, but it's really much slower than React. sometimes the page doesn't want to load at all.  I was installing all styled-icons packs also in this project.

But the interesting point that this slowness in development mode only, in production there no thing .

If you are interested to take a deep look , i have added you as a contributor in a Next.JS project i'm working on it ,take a look and we all hope we can make styled-icons better.

**Comment by jacobwgillespie** [comment]
@AhmedTohamy01 thanks for sharing the repository, I was able to take a look and capture some timings.

I first checked to make sure tree shaking was working - if you don't already know, the Webpack bundle analyzer is a nice way to investigate what modules are included in the built bundle, and the https://www.npmjs.com/package/@next/bundle-analyzer package makes this easy with Next. You run `npm install @next/bundle-analyzer` and add the following to your `next.config.js`:

```javascript
const withBundleAnalyzer = require('@next/bundle-analyzer')({
  enabled: process.env.ANALYZE === 'true',
})
module.exports = withBundleAnalyzer({})
```

Then, running `ANALYZE=true npm run build` will open two browser windows for the client and server bundles...

Anyways, I was able to determine that tree shaking is working, so only the icons you are directly using appear in the bundle.

So in that case, the slowdown seems to be due to Webpack inside Next parsing the icon JavaScript files for icons that aren't included. They're parsed, but later removed from the bundle, but it's that initial parse step that slows things down.

In order to capture some timings, I ran `rm -rf .next && time npm run build` so that each run would build the site from scratch, deleting any cache beforehand. I ran each build four times to collect different samples.

For the current `main` branch with no modifications:

<table>
<tr><th>Time with no modifications (seconds)</th></tr>
<tr><td>44.807</td></tr>
<tr><td>41.912</td></tr>
<tr><td>61.56</td></tr>
<tr><td>45.065</td></tr>
</table>

I also removed styled icons entirely from your project and ran builds with all icons removed:

<table>
<tr><th>Time with icons removed (seconds)</th></tr>
<tr><td>11.358</td></tr>
<tr><td>9.889</td></tr>
<tr><td>11.109</td></tr>
<tr><td>15.949</td></tr>
</table>

I then when back to the `main` branch and removed the `styled-icons` package from your `package.json` and replaced it with just the modules you use:

```json
    "@styled-icons/bootstrap": "^10.25.0",
    "@styled-icons/boxicons-solid": "^10.23.0",
    "@styled-icons/evaicons-outline": "^10.18.0",
    "@styled-icons/evaicons-solid": "^10.18.0",
    "@styled-icons/fa-solid": "^10.26.0",
    "@styled-icons/heroicons-solid": "^10.19.0",
    "@styled-icons/ionicons-outline": "^10.28.0",
    "@styled-icons/ionicons-sharp": "^10.28.0",
    "@styled-icons/ionicons-solid": "^10.28.0",
    "@styled-icons/material-twotone": "^10.28.0",
```

That improved build time a lot, by almost 50%:

<table>
<tr><th>Time after only installing the used packs (seconds)</th></tr>
<tr><td>19.124</td></tr>
<tr><td>24.538</td></tr>
<tr><td>29.981</td></tr>
<tr><td>32.439</td></tr>
</table>

It's still about twice as slow on a cold build as not having the icons at all though, mostly because it still has to parse all the icon pack icons that aren't imported before it removes them from tree shaking.

So as one final step, I changed the imports to direct icon imports. This may be close to what you were looking for actually. Like this:

```javascript
// Instead of this
import {IconName} from '@styled-icons/pack-name'

// You use this
import {IconName} from '@style-icons/pack-name/IconName'
```

This is more tedious, as you have to add a new import line every time you import an icon, however it now only has to parse the JavaScript files during build for the actual icons you import, so the build times drop down to basically the same as not importing any icons at all 🎉 

<table>
<tr><th>Time after direct icon imports (seconds)</th></tr>
<tr><td>11.101</td></tr>
<tr><td>9.775</td></tr>
<tr><td>10.362</td></tr>
<tr><td>9.815</td></tr>
</table>

So it's probably up to you, but either uninstalling `styled-icons` and only installing the `@styled-icons/pack-name` packages, or doing that and also using direct icon imports, and you should be able to bring your build time back to something quick!

---

One other note, all the above only measures build time from a cold cache. When you run a build in dev, it can re-use previous work, so you may find that you're okay importing icons in a way that's a little slow during a cold build because it's not noticeable during a rebuild.

On that topic, I'd recommend upgrading your Next version to `10.2.0` if you can. It significantly speeds up rebuilds, with 60% faster builds from cache and 100-200ms faster dev reload time. And you get it for free just by upgrading Next 🙂

**Comment by AhmedTohamy01** [comment]
@jacobwgillespie 

Hey buddy, 

First of all , I'm so sorry for my late reply, this was really out of my hand.

Second, You are awesome man :)

Your explanation for the problem and the solution was really awesome and extremely helpful.

So, u will install only the packs which i need , and i don't mind also to import icons individually like this, it's not a big deal.
` import {IconName} from '@style-icons/pack-name/IconName'`

I can't say how much you make my life easier, I like this library so much and i hope it became better and better :) 

Thanks again buddy, much appreciated

**Comment by jacobwgillespie** [comment]
Perfect, thanks for the kind words, and I'm glad that was helpful and that you're finding the library useful! 🎉

**Comment by AhmedTohamy01** [comment]
@jacobwgillespie Thanks buddy.

We will wait for your next awesome library :)
