### ISSUE TITLE
iconVerticalAlignment exposed but errors with TS

### ISSUE THREAD

**Issue by mmahalwy** [styled-icons/styled-icons#1322]
See:
![image](https://user-images.githubusercontent.com/3749095/87118062-6370eb80-c248-11ea-82a2-e912229689ad.png)

This actually works and aligns the icon, but TS is unhappy with the type as it's not exported.

**Comment by jacobwgillespie** [comment]
Hey, yes that does happen to work, though it's not intentional. 🙂 You can think of the `iconXXX` props as internal, so `iconVerticalAlign` is supposed to be the default vertical alignment value from the icon pack itself, as some icon packs intend to have a `-0.125em` vertical alignment, and then you would directly style the `vertical-align` CSS property to override.

In a future version of Styled Icons, those props will probably be renamed to `$verticalAlign`, which will make Styled Components hide them externally (the latest version doesn't pass props through when they're prefixed with a `$`).

What you probably want to do instead is directly set the CSS for `vertical-align`. There's a few ways you could do this.

Create a new styled icon:

```javascript
const StyledMap = styled(Map)`
  vertical-align: text-top;
`

<StyledMap size={16} />
```

Or add an inline `css` prop (requires the Styled Components Babel plugin):

```javascript
<Map css="vertical-align: text-top" size={16} />
```

Or probably my favorite, if you want all the icons in a particular part of your app to share the same style, you can create a wrapper element that applies a style to all icons contained in that wrapper, or otherwise just add a rule targeting `StyledIconBase` to an existing parent component:

```jsx
import styled from 'styled-components'
import {StyledIconBase} from '@styled-icons/styled-icon'

const Wrapper = styled.div`
  ${StyledIconBase} {
    vertical-align: text-top;
  }
`

// All the icons inside the wrapper get the vertical-align attribute
<Wrapper>
  <Map size={16} />
  <Link size={16} />
  <Tag size={16} />
</Wrapper>
```

**Comment by mmahalwy** [comment]
Oh yeah, the 3rd option is the coolest. I didn't catch that in the README. I think this is (imho) a better example than the one in the README. Cool to port it over?

**Comment by jacobwgillespie** [comment]
Definitely! It's supposed to be here: https://github.com/styled-icons/styled-icons#base-icon-styles. But that's not exactly the clearest section.

**Comment by mmahalwy** [comment]
Yeah, this is the key part:
```tsx
// All the icons inside the wrapper get the vertical-align attribute
<Wrapper>
  <Map size={16} />
  <Link size={16} />
  <Tag size={16} />
</Wrapper>
```
