### ISSUE TITLE
remix-line icon pack does not contain the hashtag icon

### ISSUE THREAD

**Issue by raunaqgupta** [styled-icons/styled-icons#1717]
I'm not sure how packages are kept up-to-date but this particular icon is not available via `styled-icons`

![image](https://user-images.githubusercontent.com/623670/113783517-b6e56c80-96e8-11eb-9c62-4fae5badf7e5.png)

**Comment by jacobwgillespie** [comment]
Good catch, thanks for reporting this. It looks like the issue is that Remix icons are typically either line or fill icons (hence our `@styled-icons/remix-line` and `@styled-icons/remix-fill` packs), but the editor icons are not, there is only one variant for those.

I'll publish a new module, `@styled-icons/remix-editor`, shortly with the missing icons. 👍

**Comment by jacobwgillespie** [comment]
The `@styled-icons/remix-editor` package has been published, thanks again! 🎉
