### ISSUE TITLE
Documentation update for "Base Icon Styles"

### ISSUE THREAD

**Issue by KevinKra** [styled-icons/styled-icons#1835]
Could the "Base Icon Styles" documentation be expanded more? Currently it's vague and I'm having trouble understanding how it's intended to be implemented. I created a SO post here and have tried a bunch of different things and so far nothing is working.

https://stackoverflow.com/questions/68521158/how-to-setup-styled-components-base-icon-styles

**Comment by jacobwgillespie** [comment]
@KevinKra hey, thanks for opening the issue!

So the base icon styles are intended to be used how you are using them in your Stack Overflow post - if you reference `StyledIconBase` in a style, then those styles get applied to all icons that are children of that element. So if you had some CSS you wanted to apply to all icons in your application, you could add that CSS to a wrapper element that surrounded your whole app, etc.

It does appear that your code example works though - take a look at https://codesandbox.io/s/jolly-mendel-9q4c5?file=/src/BrandIcon.tsx.

As you can see there, the icon color is orange, since the wrapper style says the color should be orange, rather than the default of red. Let me know if that's not what you were expecting though.

**Comment by KevinKra** [comment]
Interesting, thank you for the feedback! I'll need to revisit this and mess around with it some more, for whatever reason in my implementation the color wasn't changing. Perhaps the issue lies elsewhere.

**Comment by KevinKra** [comment]
Yep, play around with it some more and it appears to be working now. Thank you again.

**Comment by jacobwgillespie** [comment]
Perfect, glad to hear! 🎉
